### PR TITLE
Prevent failed engines from re-activating.

### LINKED ISSUE #160: Engine Shutdown Easily "Fixed"
I've discovered that an "engine shutdown" failure can be fixed despite TestFlight no longer supporting repair functionality... sort of.

The bug can be reproduced in KSP 1.2.2, with ModuleManager 2.7.5, TestFlight 1.8.0.1, and [this config file](https://gist.github.com/Starstrider42/749685b1c0038d5d65916b286dafb7d1) instead of the default stock ones. I started a sandbox game, cheated the Orbiter 1A into orbit, and applied thrust until an engine failed. Right-clicking on the affected engine shows the normal "Activate Engine" button:
screenshot4
Clicking it restores functionality to the engine, although the engine is still marked in red in the staging list and is still marked as failed in the TF window. However, it works just fine, and is immune to further failures:
screenshot9

I suspect a similar bug applies to ignition failures, but I haven't been able to trigger one yet.

### PR DESCRIPTION
**Pull request by Starstrider42**
This commit suppresses the Activate/Deactivate Engine right-click command when an engine experiences a shutdown failure, and restores the GUI when the engine is repaired. I don't understand why `ModuleEngines` requires me to set the events' `guiActive` when other modules make do with just `active`. Fixes #160.

I have only tested this fix on stock KSP, not RO.

### CODE REVIEW

File: TestFlightFailure_IgnitionFail.cs [hunk 1]
```diff
@@ -148,6 +153,9 @@ public override float DoRepair()
                 EngineHandler engine = engines[i];
                 {
                     engine.engine.Shutdown();
```
Comment (Starstrider42) [inline TestFlightFailure_IgnitionFail.cs]: @jwvanderbeck, do you remember what the logic was behind making an ignitor repair shut down the engine? This was added in commit 1781eae8fc031eb78015afce8391adff7f4256aa.

Comment (jwvanderbeck) [inline TestFlightFailure_IgnitionFail.cs]: As I recall it wasn't so much causing the engine to fail upon repair, but just shut it down in case it was already running.  It is a bit hazy but I seem to recall a situation where you could ignite the engine, get a failure and then if you repaired the failure the engine would immediately jump back into the running state.  So this was just to ensure that if it failed to ignite, and then you fixed it, you would have to re-ignite it using up an ignition.
